name: '2# Update Blocklist to Cloudflare Gateway'
on:
  workflow_dispatch:
  workflow_run:
    workflows: [1# Update Blocklist File]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_API_EMAIL: ${{ secrets.CF_API_EMAIL }}
      CF_API_ACCOUNT_ID: ${{ secrets.CF_API_ACCOUNT_ID }}
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Python script
      run: python create-upload.py
