name: 'TEST'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN: ${{ secrets.CF_API_KEY }}
      CF_API_EMAIL: ${{ secrets.CF_API_EMAIL }}
      CF_API_ACCOUNT_ID: ${{ secrets.CF_API_ACCOUNT_ID }}
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Python script
      run: python cloudflare_adblock.py