name: Cloudflare Adblock

on:
  push:
    branches:
      - main

jobs:
  adblock:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Download, split, upload and create rules
      env:
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        CF_API_ACCOUNT_ID: ${{ secrets.CF_API_ACCOUNT_ID }}
        CF_API_EMAIL: ${{ secrets.CF_API_EMAIL }}
      run: |
        python cloudflare_adblock.py
