name: '3# Get Account ID'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_API_EMAIL: ${{ secrets.CF_API_EMAIL }}
    steps:
    - uses: actions/checkout@v3.5.0
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Python script
      run: python account-id.py
