name: Clear Action Runs

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  clear-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Delete workflow runs
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          RUNS=$(curl -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$OWNER/$REPO/actions/runs" | jq -r '.workflow_runs[].id')
          for run in $RUNS; do
            curl -X DELETE -s -H "Authorization: token $TOKEN" "https://api.github.com/repos/$OWNER/$REPO/actions/runs/$run"
          done