name: My Python Workflow
on:
  workflow_run:
    workflows: ["Update Domain List"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_API_EMAIL: ${{ secrets.CF_API_EMAIL }}
      CF_API_ACCOUNT_ID: ${{ secrets.CF_API_ACCOUNT_ID }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Python script
      run: python main.py
